### ISSUE TITLE
Recheck throws error `Error: write EPIPE`

### ISSUE THREAD

**Issue by thernstig** [makenowjust-labs/recheck#758]
# What is the problem?

```js
import { check } from 'recheck';

await check('^(a|a)*$', '');
```

gives:
```sh
[Running] node "/home/userA/code/projectA/regexTest.js"
node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at afterWriteDispatched (node:internal/stream_base_commons:160:15)
    at writeGeneric (node:internal/stream_base_commons:151:3)
    at Socket._writeGeneric (node:net:917:11)
    at Socket._write (node:net:929:8)
    at writeOrBuffer (node:internal/streams/writable:392:12)
    at _write (node:internal/streams/writable:333:10)
    at Writable.write (node:internal/streams/writable:337:10)
    at /home/userA/code/projectA/node_modules/recheck/lib/main.js:2:20
    at new Promise (<anonymous>)
    at FA.request (/home/userA/code/projectA/node_modules/recheck/lib/main.js:1:1513)
Emitted 'error' event on Socket instance at:
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}

Node.js v18.12.1
```

It is like this in 4.4.2 and 4.4.3 but in 4.4.1 it works.

# How to fix the problem?

No idea.

# Related issues

None.

**Comment by thernstig** [comment]
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.3 LTS"

node v18.12.1

I had a colleague test this as well and they had the same result, but they are also on the same kind of machine.

Is it something in the code changes in 4.4.2 that could cause this?

**Comment by makenowjust** [comment]
Thanks. I can reproduce the bug on linux machine.

4.4.2 has no big change on the source code, so I guess some dependencies are wrong.

**Comment by makenowjust** [comment]
I can suggest setting the environment variable `RECHECK_BACKEND=worker` as a temporary solution? (or `RECHECK_BACKEND=pure`) Performance may be degraded, but it may solve the problem.
(See [the document](https://makenowjust-labs.github.io/recheck/docs/usage/as-javascript-library/#backend).)

I need more time to investigate the root cause.

**Comment by thernstig** [comment]
@makenowjust great, maybe add a test case running all the tests also on Ubuntu in your Github tests?

**Comment by makenowjust** [comment]
I tried the dirty patch `sed -i.bak 's/"ignore"/"inherit"/' node_modules/recheck/lib/main.js`, and the following error messages are shown after the patch.

```
recheck/packages/recheck-linux-x64/recheck: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by recheck/packages/recheck-linux-x64/recheck)
recheck/packages/recheck-linux-x64/recheck: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by recheck/packages/recheck-linux-x64/recheck)
```

That is, the bug is probably caused by libc being too new in the built environment. Indeed, we use `ubuntu-latest` on CI, and the version of ubuntu-latest was updated by the release of 4.4.2. We should fix the version of CI environment.

@thernstig Almost cases are tested [here](https://github.com/makenowjust-labs/recheck/blob/main/packages/recheck/src/main.test.ts), but some cases are skipped because of preventing too slow to run CI. This case seems very special, so we cannot catch it in the CI.

**Comment by thernstig** [comment]
@makenowjust maybe you could for the main flow of just doing this would want to test on more versions?

```js
import { check } from 'recheck';

await check('^(a|a)*$', '');
```

i.e. just run such a test case on multiple versions of e.g. Ubuntu. But I realize that is maybe a rare case that it would break, so possibly not worth it.

**Comment by makenowjust** [comment]
CI environment versions are updated. Could you download a new binary from [here](https://github.com/makenowjust-labs/recheck/actions/runs/4163277614), put it to `node_modules/recheck-linux-x64/recheck`, and try it?

@thernstig The CI takes 7-13 minutes, and I feel it is too slow. I wouldn't add more CI tasks if at all possible.

**Comment by thernstig** [comment]
@makenowjust seems to work.

**Comment by makenowjust** [comment]
Thank you. I am going to publish a new version tomorrow.

**Comment by makenowjust** [comment]
Close. The new version is published.
