### ISSUE TITLE
MacOS ARM64 native binaries

### ISSUE THREAD

**Issue by Cellule** [makenowjust-labs/recheck#956]
# What is the problem?

On Apple processor chips m1/m2 ARM64, it seems recheck fallsback to java implementation.
While it achieves the end goal, I was wondering if you can provide native ARM64 binaries or even use x64 emulation (unclear if that would be better than java runtime)

# How to fix the problem?

1. Provide recheck-macos-arm64 package
2. Try x64 emulation ?

**Comment by makenowjust** [comment]
Binaries are built by GitHub Actions. However, GH Actions does not support arm macos runner for now.

Related issue: https://github.com/github/roadmap/issues/528

Note that you could use JVM backend on arm macos if JVM is installed. It runs as fast as native (or faster than native due to JIT compile.)

**Comment by dvergnes** [comment]
Github actions now supports arm macos https://github.blog/2023-10-02-introducing-the-new-apple-silicon-powered-m1-macos-larger-runner-for-github-actions/, any chance to get an update on this ticket?

**Comment by makenowjust** [comment]
As far as I know it is a paid feature. I don't make any profit from recheck, so I can't use it.

**Comment by makenowjust** [comment]
Good news https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source/
